### PR TITLE
Add pt-br to languages

### PR DESCRIPTION
**Pull request by marimeireles**
Please let me know if I need to do something else.
Thanks! 🌸

### CODE REVIEW

**Comment by marimeireles** [comment]
Related to issue #20.

**Review by manyinsects — COMMENTED** [review]
rubber-stamping, if you know anyone who would like to review this and can speak the language, feel free to do so! i'll let this sit for a day or so

**Comment by marimeireles** [comment]
@fmoko I posted in a Brazilian Rust group. Hopefully someone will revise it :)

**Review by leoyvens — APPROVED** [review]
lgtm

**Pull request merged**
